# Google API RAG System Configuration

# 경로 설정
paths:
  api_data_dir: "./GOOGLE_API_DATA"
  api_qa_dir: "./GOOGLE_API_DATA/GOOGLE_API_DATA_QA"
  chroma_db_dir: "./chroma_google_api_db"

# 모델 설정
models:
  # GPT-4o 설정
  gpt4o:
    enabled: true
    model_name: "gpt-4o"
    temperature: 0.7
    max_tokens: 1024
    # API 키는 환경변수 OPENAI_API_KEY로 설정

  # 기본 모델 선택 (gpt4o 또는 qwen)
  default: "gpt4o"

# 임베딩 설정
embedding:
  model_name: "BAAI/bge-m3"
  device: "auto"  # cuda, cpu, auto
  normalize: true

# 검색 설정
retrieval:
  search_type: "similarity_score_threshold"
  top_k: 10
  score_threshold: 0.3
  chunk_size: 1500
  chunk_overlap: 300

# 프롬프트 설정
prompts:
  system_prompt_gpt4o: |
    You are a Google API expert. Provide accurate and practical answers to help developers.
    Include exact API method names, parameters, and code examples.
    Answer in Korean.

  system_prompt_qwen: |
    당신은 구글 API 전문가예요. 개발자에게 친근하고 도움이 되는 답변을 제공해주세요.
    정확한 API 메서드명과 파라미터를 알려주시고, 실제 코드 예시를 포함해주세요.
    친근한 해요체로 설명해주세요.

# 로깅 설정
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# 멀티턴 대화 설정
conversation:
  max_history: 10  # 최대 대화 히스토리 저장 개수
  enable_context_memory: true